//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadway_History.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statewide
    {
        public int ID { get; set; }
        public string COUNTY { get; set; }
        public string SignSys { get; set; }
        public string RouteNoOrigImport { get; set; }
        public Nullable<int> RouteNo { get; set; }
        public Nullable<int> SuppDes { get; set; }
        public string LocalName { get; set; }
        public Nullable<System.DateTime> DateNumber { get; set; }
        public string Method { get; set; }
        public string OriginalL { get; set; }
        public string OriginalD { get; set; }
        public string Projects { get; set; }
        public string Documents { get; set; }
        public string Comments { get; set; }
        public Nullable<int> District { get; set; }
        public bool Duplicate_OK { get; set; }
        public string RightofWay { get; set; }
        public bool ReservedRoute { get; set; }
        public string ReservedBy { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public bool CP_WorkCompleted { get; set; }
        public string Work_Comments { get; set; }
        public string CP_ProjectNo { get; set; }
        public Nullable<int> ReservedCat { get; set; }
    }
}
