//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadway_History.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Statewide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statewide()
        {
            this.Documents1 = new HashSet<Document>();
        }
    
        public int ID { get; set; }
        public string COUNTY { get; set; }
        public string SignSys { get; set; }
        public string RouteNoOrigImport { get; set; }
        public Nullable<int> RouteNo { get; set; }
        public Nullable<int> SuppDes { get; set; }
        public string LocalName { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> DateNumber { get; set; }
        public string Method { get; set; }
        public string OriginalL { get; set; }
        public string OriginalD { get; set; }
        public string Projects { get; set; }
        public string Documents { get; set; }
        public string Comments { get; set; }
        public Nullable<int> District { get; set; }
        public bool Duplicate_OK { get; set; }
        public string RightofWay { get; set; }
        public bool ReservedRoute { get; set; }
        public string ReservedBy { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public bool CP_WorkCompleted { get; set; }
        public string Work_Comments { get; set; }
        public string CP_ProjectNo { get; set; }
        public Nullable<int> ReservedCat { get; set; }
        public string Current_Status { get; set; }
        public string Add_User { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> Date_Added { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents1 { get; set; }
    }
}
